// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResultMetrics.Store.PostgreSQL;

#nullable disable

namespace ResultMetrics.Store.PostgreSQL.Migrations
{
    [DbContext(typeof(ResultMetricsDbContext))]
    [Migration("20260829143955_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResultMetrics.Store.PostgreSQL.Models.Results", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AvgExecutionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_execution_time");

                    b.Property<double>("AvgValue")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_value");

                    b.Property<double>("DeltaDateInSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("delta_date_in_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MedianValue")
                        .HasColumnType("double precision")
                        .HasColumnName("median_value");

                    b.Property<DateTime>("MinDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("min_date");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("AvgExecutionTime")
                        .HasDatabaseName("ix_results_avg_execution_time");

                    b.HasIndex("AvgValue")
                        .HasDatabaseName("ix_results_avg_value");

                    b.HasIndex("FileName")
                        .IsUnique()
                        .HasDatabaseName("ix_results_file_name");

                    b.HasIndex("MinDate")
                        .HasDatabaseName("ix_results_min_date");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("ResultMetrics.Store.PostgreSQL.Models.Values", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("double precision")
                        .HasColumnName("execution_time");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_values");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_values_date");

                    b.HasIndex("FileName")
                        .HasDatabaseName("ix_values_file_name");

                    b.ToTable("values", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
